### PR TITLE
Add support for 2018.1.* - 2018.3.*

### PR DESCRIPTION
**Pull request by AmailP**

### CODE REVIEW

**Comment by AmailP** [comment]
Fixes #61

**Comment by diannelli** [comment]
Hi Valerio,

Did you deploy these changes of your plugin to the JetBrains plugin repository?
How can I install it? 

image

**Comment by AmailP** [comment]
not yet.

You can anyway build yourself a new version of the plugin by cloning the
repository and run "./gradlew buildPlugin". You will find a zip file in the
build/distributions directory that you can manually install.

Regards

Valerio

**Comment by diannelli** [comment]
Great, it works.

Thanks.
Bye
Damiano

**Pull request merged**
